#!/usr/bin/env python3
"""The generative proposal layer (FunSearch-lite).

Stochastic mutation of the candidate table around the measured frontier:
each generation samples new (strategy, tile, warp) rows from the legal
neighborhood of the current best, rewrites variants.def, recompiles, and
pushes the new candidates through the same gates as everything else
(occupancy model -> oracle -> SASS -> timed). Rows that beat their
parents beyond the winner margin join the base table for the next
generation; the rest die.

This is the program's hook for LLM-in-the-loop proposal later: any
proposer that emits legal rows into variants.def rides the same gates.

usage: propose.py --generations 3 --per-generation 6 [--seed 0]
"""

import argparse
import json
import os
import random
import re
import subprocess
import sys

import torch
from torch.utils.cpp_extension import load

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)  # noqa: E402  (harness/space live beside this file)
from harness import make_problem, oracle_ok  # noqa: E402
from space import OCCUPANCY_BLOCKS, SMEM_PER_SM, strategy_smem  # noqa: E402

DEF_FILE = os.path.join(HERE, "variants.def")


def read_rows() -> list[tuple]:
    rows = []
    with open(DEF_FILE) as f:
        lines = f.readlines()
    for line in lines:
        m = re.match(
            r"\s*V\((\d+),\s*(\w+),\s*(\d+),\s*(\d+),\s*(\d+),"
            r"\s*(\d+),\s*(\d+)\)",
            line,
        )
        if m:
            g = m.groups()
            rows.append(
                (g[1], int(g[2]), int(g[3]), int(g[4]), int(g[5]), int(g[6]))
            )
    return rows


def write_rows(rows: list[tuple]) -> None:
    lines = [
        "// variants.def — generated by propose.py",
        "#define FOR_EACH_VARIANT(V) \\",
    ]
    for i, (s, bm, bn, bk, wr, wn) in enumerate(rows):
        line = f"V({i}, {s}, {bm}, {bn}, {bk}, {wr}, {wn})"
        lines.append(line + (" \\" if i < len(rows) - 1 else ""))
    with open(DEF_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


def row_legal(row: tuple) -> tuple[bool, str]:
    strategy, bm, bn, bk, wr, wn = row
    smem = strategy_smem(strategy, bm, bn, bk)
    if smem * OCCUPANCY_BLOCKS > SMEM_PER_SM:
        return False, f"smem {smem}B x2 > 64KiB"
    if strategy in ("pipe", "pipe3") and (
        bk != 32 or wr * wn * 32 != max(bm, bn) * 2
    ):
        return False, "pipe3/pipe require BK=32 and THREADS=2*max(BM,BN)"
    if bn % 8 or bm % 16:
        return False, "tile not m16n8-compatible"
    return True, ""


def llm_rows(base_rows: list[tuple], n_new: int, rng: random.Random) -> list[tuple]:
    """Optional LLM proposer. Active when VLLM_TURING_PROPOSER_URL and
    VLLM_TURING_PROPOSER_MODEL are set (OpenAI-compatible chat endpoint).
    Asks for n_new legal (strategy, BM, BN, BK, WR, WN) rows near the
    measured frontier; every returned row still passes row_legal and the
    standard gates, so a hallucinated row costs one rejected candidate,
    not a wrong answer. Falls back to stochastic mutation when the env
    is unset or the call/parse fails."""
    url = os.environ.get("VLLM_TURING_PROPOSER_URL")
    model = os.environ.get("VLLM_TURING_PROPOSER_MODEL")
    if not url or not model:
        return [mutate(base_rows, rng) for _ in range(n_new)]
    import json as _json
    import urllib.request
    prompt = (
        "You propose GPU kernel tile configurations as JSON rows "
        '[strategy, BM, BN, BK, WARPS_R, WARPS_N]. Legal: strategy in '
        "{staged, regdeq, regdeq2, pipe, pipe3}; BM in {32,64,128}; BN in "
        "{64,128,256}; BK 64 (pipe/pipe3: 32); pipe/pipe3 need "
        "WARPS_R*WARPS_N*32 == max(BM,BN)*2. Shared memory per block must "
        "stay under 32 KiB. Existing rows: "
        f"{_json.dumps([list(r) for r in base_rows])}. "
        f"Propose exactly {n_new} NEW rows as a bare JSON array."
    )
    try:
        req = urllib.request.Request(
            url,
            data=_json.dumps({"model": model,
                              "messages": [{"role": "user",
                                            "content": prompt}],
                              "temperature": 0.8}).encode(),
            headers={"Content-Type": "application/json",
                     "Authorization": "Bearer "
                     + os.environ.get("OPENAI_API_KEY", "")})
        with urllib.request.urlopen(req, timeout=60) as r:
            text = _json.loads(r.read())["choices"][0]["message"]["content"]
        arr = _json.loads(text[text.index("["): text.rindex("]") + 1])
        out = []
        for row in arr:
            if len(row) != 6:
                continue
            row = (str(row[0]),) + tuple(int(x) for x in row[1:])
            if row_legal(row)[0] and row not in base_rows:
                out.append(row)
            if len(out) >= n_new:
                break
        if out:
            return out
    except Exception as exc:
        print(f"llm proposer failed ({exc}); falling back to mutation")
    return [mutate(base_rows, rng) for _ in range(n_new)]


def mutate(rows: list[tuple], rng: random.Random) -> tuple:
    s, bm, bn, bk, wr, wn = rng.choice(rows)
    bm = rng.choice([b for b in (32, 64, 128) if b <= bm * 2] or [64])
    bn = rng.choice([64, 128, 256])
    wr = bm // 16
    wn = rng.choice([1, 2])
    if s == "pipe":
        bk = 32
        wn = max(bm, bn) // bm
    else:
        bk = 64
    return (s, bm, bn, bk, wr, wn)


def rebuild_ext():
    # variants.def is included by turing_search.cu but invisible to the
    # extension builder's source hash; touch the tracked file
    subprocess.run(["touch", "turing_search.cu"])
    subprocess.run(
        [
            "/opt/cuda/bin/nvcc",
            "-arch=sm_75",
            "-O3",
            "-I",
            ".",
            "-c",
            "turing_search.cu",
            "-o",
            "turing_search.o",
        ],
        check=True,
        capture_output=True,
    )
    return load(
        name="turing_search_drv",
        sources=[os.path.join(HERE, "driver.cu"),
                 os.path.join(HERE, "turing_search.cu")],
        extra_cuda_cflags=["-arch=sm_75", "-O3"],
        verbose=False,
    )


def evaluate(ext, vi: int, msweeps, seed: int = 5) -> tuple[float, bool]:
    """Worst-case TFLOP/s over the sweep; 0.0 on oracle failure."""
    worst = float("inf")
    for M in msweeps:
        A, Q, S, empty, ref_fn = make_problem(4096, 4096, M, seed=seed)
        ok, _ = oracle_ok(ext, vi, A, Q, S, empty, G=128, nz=1, ref_fn=ref_fn)
        if not ok:
            return 0.0, False
        s, e = torch.cuda.Event(True), torch.cuda.Event(True)
        for _ in range(3):
            ext.launch(vi, A, Q, S, empty, 128, 1)
        torch.cuda.synchronize()
        s.record()
        ext.launch(vi, A, Q, S, empty, 128, 1)
        e.record()
        torch.cuda.synchronize()
        worst = min(worst, 2 * M * 4096 * 4096 / (s.elapsed_time(e) * 1e-3) / 1e12)
    return worst, True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--generations", type=int, default=2)
    ap.add_argument("--per-generation", type=int, default=6)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--proposer", choices=["mutate", "llm"], default="mutate")
    args = ap.parse_args()
    rng = random.Random(args.seed)

    base_rows = read_rows()
    torch.manual_seed(args.seed)
    report = {"generations": [], "kept": []}
    for gen in range(args.generations):
        proposals, seen = [], {r[1:] for r in base_rows}
        while len(proposals) < args.per_generation:
            row = (llm_rows(base_rows, 1, rng)[0]
                   if args.proposer == "llm" else mutate(base_rows, rng))
            if row in seen or not row_legal(row)[0]:
                continue
            seen.add(row)
            proposals.append(row)
        rows = base_rows + proposals
        write_rows(rows)
        try:
            ext = rebuild_ext()
        except Exception as exc:
            print(f"gen{gen}: compile failed, reverting: {exc}")
            write_rows(base_rows)
            continue
        n0 = len(base_rows)
        kept = []
        print(f"gen{gen}: proposing {[p[0] + '_' + str(p[1:]) for p in proposals]}")
        for j, row in enumerate(proposals):
            vi = n0 + j
            tf, ok = evaluate(ext, vi, msweeps=[8, 512])
            parent = [r for r in base_rows if r[1] == row[1]]
            ptf = 0.0
            if parent:
                pvi = rows.index(parent[0])
                ptf, _ = evaluate(ext, pvi, msweeps=[8, 512])
            margin = max(0.05, 3 * 0.004)
            keep = ok and tf > ptf * (1 + margin)
            print(
                f"gen{gen}: {row[0]}_{row[1]}_{row[2]}_{row[3]}"
                f" w{row[4]}x{row[5]}: {tf:.2f} TF/s"
                f" (parent {ptf:.2f}) -> {'KEPT' if keep else 'died'}"
            )
            entry = {"row": row, "tflops": round(tf, 2), "kept": keep}
            report["generations"].append(entry)
            if keep:
                kept.append(row)
        if kept:
            base_rows = sorted(base_rows + kept, key=str)
            report["kept"].append([list(r) for r in kept])
            write_rows(base_rows)
        else:
            write_rows(base_rows)
    report["final_rows"] = [list(r) for r in read_rows()]
    with open(os.path.join(HERE, "proposals-report.json"), "w") as f:
        json.dump(report, f, indent=2)
    print(
        f"final table: {len(report['final_rows'])} rows"
        f" -> variants.def / proposals-report.json"
    )


if __name__ == "__main__":
    main()
